<?php
$news_sources_icons = [

['id' => 'abc-news', 'logo' => 'https://icons.better-idea.org/icon?url=http://abcnews.go.com&size=70..120..200'],
['id' => 'abc-news-au', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.abc.net.au/news&size=70..120..200'],

['id' => 'aftenpost', 'logo' => 'https://icons.better-idea.org/icon?url=https://www.aftenposten.no&size=70..120..200'],



['id' => 'al-jazeera-english', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.aljazeera.com&size=70..120..200'],
['id' => 'ansi', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.ansa.it&size=70..120..200'],
['id' => 'argaam', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.argaam.com&size=70..120..200'],

['id' => 'ars-technica', 'logo' => 'https://icons.better-idea.org/icon?url=http://arstechnica.com&size=70..120..200'],

['id' => 'ars-news', 'logo' => 'https://icons.better-idea.org/icon?url=https://arynews.tv/ud/&size=70..120..200'],

['id' => 'associated-press', 'logo' => 'https://icons.better-idea.org/icon?url=http://bigstory.ap.org&size=70..120..200'],
['id' => 'australian-financial-review', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.afr.com&size=70..120..200'],

['id' => 'bbc-news', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.bbc.co.uk/news&size=70..120..200'],
['id' => 'bbc-sport', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.bbc.co.uk/sport&size=70..120..200'],
['id' => 'bild', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.bild.de&size=70..120..200'],
['id' => 'bloomberg', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.bloomberg.com&size=70..120..200'],
['id' => 'breitbart-news', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.breitbart.com&size=70..120..200'],
['id' => 'business-insider', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.businessinsider.com&size=70..120..200'],
['id' => 'business-insider-uk', 'logo' => 'https://icons.better-idea.org/icon?url=http://uk.businessinsider.com&size=70..120..200'],
['id' => 'buzzfeed', 'logo' => 'https://icons.better-idea.org/icon?url=https://www.buzzfeed.com&size=70..120..200'],
['id' => 'cnbc', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.cnbc.com&size=70..120..200'],
['id' => 'cnn', 'logo' => 'https://icons.better-idea.org/icon?url=http://us.cnn.com&size=70..120..200'],
['id' => 'daily-mail', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.dailymail.co.uk/home/index.html&size=70..120..200'],
['id' => 'der-tagesspiegel', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.tagesspiegel.de&size=70..120..200'],
['id' => 'die-zeit', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.zeit.de/index&size=70..120..200'],
['id' => 'engadget', 'logo' => 'https://icons.better-idea.org/icon?url=https://www.engadget.com&size=70..120..200'],
['id' => 'entertainment-weekly', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.ew.com&size=70..120..200'],
['id' => 'espn', 'logo' => 'https://icons.better-idea.org/icon?url=http://espn.go.com&size=70..120..200'],
['id' => 'espn-cric-info', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.espncricinfo.com/&size=70..120..200'],
['id' => 'financial-times', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.ft.com/home/uk&size=70..120..200'],
['id' => 'focus', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.focus.de&size=70..120..200'],
['id' => 'football-italia', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.football-italia.net&size=70..120..200'],
['id' => 'fortune', 'logo' => 'https://icons.better-idea.org/icon?url=http://fortune.com&size=70..120..200'],
['id' => 'four-four-two', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.fourfourtwo.com/news&size=70..120..200'],
['id' => 'fox-sports', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.foxsports.com&size=70..120..200'],
['id' => 'google-news', 'logo' => 'https://icons.better-idea.org/icon?url=https://news.google.co.uk&size=70..120..200'],
['id' => 'gruenderszene', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.gruenderszene.de&size=70..120..200'],
['id' => 'hacker-news', 'logo' => 'https://icons.better-idea.org/icon?url=https://news.ycombinator.com&size=70..120..200'],
['id' => 'handlesblatt', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.handelsblatt.com&size=70..120..200'],
['id' => 'ign', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.ign.com&size=70..120..200'],
['id' => 'independent', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.independent.co.uk&size=70..120..200'],
['id' => 'mashable', 'logo' => 'https://icons.better-idea.org/icon?url=http://mashable.com&size=70..120..200'],
['id' => 'metro', 'logo' => 'https://icons.better-idea.org/icon?url=http://metro.co.uk&size=70..120..200'],
['id' => 'mirror', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.mirror.co.uk/&size=70..120..200'],
['id' => 'mtv-news', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.mtv.com/news&size=70..120..200'],
['id' => 'mtv-news-uk', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.mtv.co.uk/news&size=70..120..200'],
['id' => 'national-geographic', 'logo' => 'https://icons.better-idea.org/icon?url=http://news.nationalgeographic.com&size=70..120..200'],
['id' => 'new-scientist', 'logo' => 'https://icons.better-idea.org/icon?url=https://www.newscientist.com/section/news&size=70..120..200'],
['id' => 'newsweek', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.newsweek.com&size=70..120..200'],
['id' => 'new-york-magazine', 'logo' => 'https://icons.better-idea.org/icon?url=http://nymag.com&size=70..120..200'],
['id' => 'nfl-news', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.nfl.com/news&size=70..120..200'],
['id' => 'polygon', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.polygon.com&size=70..120..200'],
['id' => 'recode', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.recode.net&size=70..120..200'],
['id' => 'reddit-r-all', 'logo' => 'https://icons.better-idea.org/icon?url=https://www.reddit.com/r/all&size=70..120..200'],
['id' => 'reuters', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.reuters.com&size=70..120..200'],
['id' => 'spiegel-online', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.spiegel.de&size=70..120..200'],
['id' => 't3n', 'logo' => 'https://icons.better-idea.org/icon?url=http://t3n.de&size=70..120..200'],
['id' => 'talksport', 'logo' => 'https://icons.better-idea.org/icon?url=http://talksport.com&size=70..120..200'],
['id' => 'tech-crunch', 'logo' => 'https://icons.better-idea.org/icon?url=https://techcrunch.com&size=70..120..200'],
['id' => 'tech-radar', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.techradar.com&size=70..120..200'],
['id' => 'the-economist', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.economist.com&size=70..120..200'],
['id' => 'the-guardian-au', 'logo' => 'https://icons.better-idea.org/icon?url=https://www.theguardian.com/au&size=70..120..200'],
['id' => 'the-guardian-uk', 'logo' => 'https://icons.better-idea.org/icon?url=https://www.theguardian.com/uk&size=70..120..200'],
['id' => 'the-hindu', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.thehindu.com&size=70..120..200'],
['id' => 'the-huffington-post', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.huffingtonpost.com&size=70..120..200'],
['id' => 'the-lad-bible', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.theladbible.com&size=70..120..200'],
['id' => 'the-new-york-times', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.nytimes.com&size=70..120..200'],
['id' => 'the-next-web', 'logo' => 'https://icons.better-idea.org/icon?url=http://thenextweb.com&size=70..120..200'],
['id' => 'the-sport-bible', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.thesportbible.com&size=70..120..200'],
['id' => 'the-telegraph', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.telegraph.co.uk&size=70..120..200'],
['id' => 'the-times-of-india', 'logo' => 'https://icons.better-idea.org/icon?url=http://timesofindia.indiatimes.com&size=70..120..200'],
['id' => 'the-verge', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.theverge.com&size=70..120..200'],
['id' => 'the-wall-street-journal', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.wsj.com&size=70..120..200'],
['id' => 'the-washington-post', 'logo' => 'https://icons.better-idea.org/icon?url=https://www.washingtonpost.com&size=70..120..200'],
['id' => 'time', 'logo' => 'https://icons.better-idea.org/icon?url=http://time.com&size=70..120..200'],
['id' => 'usa-today', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.usatoday.com/news&size=70..120..200'],
['id' => 'wired-de', 'logo' => 'https://icons.better-idea.org/icon?url=https://www.wired.de&size=70..120..200'],
['id' => 'wirtshcafts-woche', 'logo' => 'https://icons.better-idea.org/icon?url=http://www.wiwo.de&size=70..120..200'],



];
